language: objective-c
osx_image: xcode63
script:
- xcodebuild -project swicat/TestApp/TestApp.xcodeproj -scheme "TestApp" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 5" ONLY_ACTIVE_ARCH=NO test
