language: objective-c
osx_image: xcode6.4
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
script:
  - xctool -project swicat/TestApp/TestApp.xcodeproj -scheme TestApp -sdk iphonesimulator run-tests
